// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto

#include "node.pb.h"
#include "node.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace node {

static const char* DataServer_method_names[] = {
  "/node.DataServer/getNode",
};

std::unique_ptr< DataServer::Stub> DataServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DataServer::Stub> stub(new DataServer::Stub(channel, options));
  return stub;
}

DataServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getNode_(DataServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DataServer::Stub::getNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::node::ResponseNode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::node::RequestNode, ::node::ResponseNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getNode_, context, request, response);
}

void DataServer::Stub::async::getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::node::RequestNode, ::node::ResponseNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getNode_, context, request, response, std::move(f));
}

void DataServer::Stub::async::getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::node::ResponseNode>* DataServer::Stub::PrepareAsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::node::ResponseNode, ::node::RequestNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::node::ResponseNode>* DataServer::Stub::AsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

DataServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DataServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DataServer::Service, ::node::RequestNode, ::node::ResponseNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DataServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::node::RequestNode* req,
             ::node::ResponseNode* resp) {
               return service->getNode(ctx, req, resp);
             }, this)));
}

DataServer::Service::~Service() {
}

::grpc::Status DataServer::Service::getNode(::grpc::ServerContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace node

