// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto
#ifndef GRPC_node_2eproto__INCLUDED
#define GRPC_node_2eproto__INCLUDED

#include "node.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace node {

class DataServer final {
 public:
  static constexpr char const* service_full_name() {
    return "node.DataServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::node::ResponseNode* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>> AsyncgetNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>>(AsyncgetNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>> PrepareAsyncgetNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>>(PrepareAsyncgetNodeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>* AsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::node::ResponseNode>* PrepareAsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::node::ResponseNode* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>> AsyncgetNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>>(AsyncgetNodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>> PrepareAsyncgetNode(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>>(PrepareAsyncgetNodeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, std::function<void(::grpc::Status)>) override;
      void getNode(::grpc::ClientContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>* AsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::node::ResponseNode>* PrepareAsyncgetNodeRaw(::grpc::ClientContext* context, const ::node::RequestNode& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getNode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getNode(::grpc::ServerContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getNode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetNode(::grpc::ServerContext* context, ::node::RequestNode* request, ::grpc::ServerAsyncResponseWriter< ::node::ResponseNode>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getNode<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getNode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::node::RequestNode, ::node::ResponseNode>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::node::RequestNode* request, ::node::ResponseNode* response) { return this->getNode(context, request, response); }));}
    void SetMessageAllocatorFor_getNode(
        ::grpc::MessageAllocator< ::node::RequestNode, ::node::ResponseNode>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::node::RequestNode, ::node::ResponseNode>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getNode(
      ::grpc::CallbackServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getNode<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getNode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getNode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetNode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getNode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getNode(context, request, response); }));
    }
    ~WithRawCallbackMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getNode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getNode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getNode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::node::RequestNode, ::node::ResponseNode>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::node::RequestNode, ::node::ResponseNode>* streamer) {
                       return this->StreamedgetNode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getNode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getNode(::grpc::ServerContext* /*context*/, const ::node::RequestNode* /*request*/, ::node::ResponseNode* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetNode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::node::RequestNode,::node::ResponseNode>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getNode<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getNode<Service > StreamedService;
};

}  // namespace node


#endif  // GRPC_node_2eproto__INCLUDED
